kubecostProductConfigs:
  # clustername should be unique for all clusters
  clusterName: kubecostProductConfigs_clusterName
  # productKey:
  #   secretname: productkey
  #   enabled: false #not needed for eval
kubecostModel:
  containerStatsEnabled: true
  cloudCost:
    enabled: true # Set to true to enable CloudCost view that gives you visibility of your Cloud provider resources cost
  etlCloudAsset: false # Set etlCloudAsset to false when cloudCost.enabled is true to reduce cluster resources consumption. Set to true to enable kubecost to include out-of-cluster cloud resources  (uses more memory)
# kubecostMetrics:
  # emitKsmV1Metrics: true # emit all KSM metrics in KSM v1. https://github.com/kubecost/docs/blob/main/ksm-metrics.md
  # emitKsmV1MetricsOnly: false # emit only the KSM metrics missing from KSM v2. Advanced users only. https://github.com/kubecost/docs/blob/main/ksm-metrics.md
prometheus:
  # Note: Even though we are disabling our bundled version of kube-state-metrics, Kubecost still emits v1 metrics.
  # Care will need to be taken in environments that already have KSM deployed.
  # For more information, see: https://github.com/kubecost/docs/blob/main/ksm-metrics.md
  kubeStateMetrics:
    enabled: false
  kube-state-metrics:
    disabled: true
  server:
    global:
      external_labels:
        # cluster_id should be unique for all clusters and the same value as .kubecostProductConfigs.clusterName
        cluster_id: kubecostProductConfigs_clusterName
  nodeExporter:
    enabled: false