kubecostProductConfigs:
  # clustername should be unique for all clusters
  clusterName: kubecostProductConfigs_clusterName
  # productKey:
  #   secretname: productkey
  #   enabled: false #not needed for eval
  cloudIntegrationSecret: cloud-integration # only runs on primary cluster
#    Enabling customPricesEnabled and defaultModelPricing instructs Kubecost to
#   # use these custom monthly resource prices when reporting node costs. Note,
#   # that the below configuration is for the monthly cost of the resource.
#   # Kubecost considers there to be 730 hours in a month. Also note, that these
#   # configurations will have no effect on metrics emitted such as
#   # `node_ram_hourly_cost` or `node_cpu_hourly_cost`.
#   # Ref: https://docs.kubecost.com/install-and-configure/install/provider-installations/air-gapped

# customPricesEnabled: true

#   customPricesEnabled: false

# defaultModelPricing:
#   enabled: true
#   CPU: "28.0"
#   spotCPU: "4.86"
#   RAM: "3.09"
#   spotRAM: "0.65"
#   GPU: "693.50"
#   spotGPU: "225.0"
#   storage: "0.04"
#   zoneNetworkEgress: "0.01"
#   regionNetworkEgress: "0.01"
#   internetNetworkEgress: "0.12"    

kubecostModel:
  federatedStorageConfigSecret: kubecost-federated-store
  
federatedETL:
  federatedCluster: true

kubecostAggregator:
  deployMethod: statefulset
  replicas: 1

prometheus:
  server:
    global:
      external_labels:
        # cluster_id should be unique for all clusters and the same value as .kubecostProductConfigs.clusterName
        cluster_id: kubecostProductConfigs_clusterName
   