kubecostProductConfigs:
  # clustername should be unique for all clusters
  clusterName: kubecostProductConfigs_clusterName
  # productKey:
  #   secretname: productkey
  #   enabled: false #not needed for eval

kubecostModel:
  federatedStorageConfigSecret: federated-store
  
federatedETL:
  federatedCluster: true

prometheus:
  server:
    global:
      external_labels:
        # cluster_id should be unique for all clusters and the same value as .kubecostProductConfigs.clusterName
        cluster_id: kubecostProductConfigs_clusterName

pricingCsv:
  enabled: true
  location:
    URI: /var/kubecost-csv/custom-pricing.csv  # local configMap or s3://bucket/path/custom-pricing.csv
    # provider: "AWS"
    # region: "us-east-1"
    # URI: s3://kc-csv-test/pricing_schema.csv # a valid file URI
    # csvAccessCredentials: pricing-schema-access-secret

# when using configmap: kubectl create configmap -n kubecost csv-pricing --from-file custom-pricing.csv
extraVolumes:
- name: kubecost-csv
  configMap:
    name: csv-pricing
extraVolumeMounts:
- name: kubecost-csv
  mountPath: /var/kubecost-csv