# Kubecost Cluster Controller for Right Sizing and Cluster Turndown
clusterController:
  enabled: false
  image:
    repository: gcr.io/kubecost1/cluster-controller
    tag: v0.16.18
  imagePullPolicy: IfNotPresent
  extraEnv: []
  # - name: EXTRA_ENV_VAR
  #   value: "extra_env_var_value"
  logLevel: info
  priorityClassName: ""
  tolerations: []
  annotations: {}
  labels: {}
  securityContext: {}
  resources: {}
  affinity: {}
  nodeSelector: {}
  primaryKubecostURL: ""  # URL for secondary clusters to connect to primary Kubecost (ex: https://kubecost.myorganization.com)
  kubecostAPIKey: ""  # API Key for secondary clusters to authenticate with primary
  createClusterControllerSecret: true  # disable if you want to use your own secret manager
  secretName: controller-secrets