kind: CostAnalyzer
apiVersion: charts.kubecost.com/v1alpha1
metadata:
  name: costanalyzer-sample
  namespace: kubecost
spec:
  clusterController:
    image:
      repository: registry.connect.redhat.com/kubecost/kubecost-cluster-controller@sha256
      tag: e2b70f89118dd1c4357cd70bc1a4d2808d309764c5ac83fca102627e8ead86db
  forecasting:
    fullImageName: 'registry.connect.redhat.com/kubecost/kubecost-modeling@sha256:8f59f8fd8696964c1b5322ca79fae78befe97323fa56c2b509bdcc67ee4c0edd'
  global:
    platforms:
      openshift:
        createMonitoringClusterRoleBinding: true
        createMonitoringResourceReaderRoleBinding: true
        enabled: true
        scc:
          clusterController: true
          networkCosts: true
          nodeExporter: true
    prometheus:
      enabled: false
      fqdn: 'https://prometheus-k8s.openshift-monitoring.svc.cluster.local:9091'
      kubeRBACProxy: true
  grafana:
    image:
      repository: registry.redhat.io/rhel9/grafana@sha256
      tag: 38bab984d94788676d2faf3e7d5b201d3379ceb33bbb461c184b6e44c228db59
    sidecar:
      image:
        repository: quay.io/kiwigrid/k8s-sidecar@sha256
        tag: 5a7861c45aab5fffb73bae9cf36e5088321564e8b3f126177736072bf6c074fb
  kubecostAggregator:
    fullImageName: 'registry.connect.redhat.com/kubecost/kubecost-cost-model@sha256:30382f1126a6c480208aa8efc73f2a824ed82381740ff950d5f576e65ec78eff'
  kubecostFrontend:
    fullImageName: 'registry.connect.redhat.com/kubecost/kubecost-frontend@sha256:e7e70713348eaa817112aff9f078e9ca57924ca83e4a792f0d93c3338d35ad19'
  kubecostModel:
    fullImageName: 'registry.connect.redhat.com/kubecost/kubecost-cost-model@sha256:30382f1126a6c480208aa8efc73f2a824ed82381740ff950d5f576e65ec78eff'
  networkCosts:
    image:
      repository: registry.connect.redhat.com/kubecost/kubecost-network-costs@sha256
      tag: c444d475be4f1aa36680bd84358e1e07303dcfe5d13a95544ad9e59f80d4a5f0
  prometheusRule:
    enabled: true
  serviceMonitor:
    enabled: true
