kind: Kubecost
apiVersion: charts.kubecost.com/v1
metadata:
  name: kubecost-sample
  namespace: kubecost
spec:
  global:
    clusterId: SET_A_UNIQUE_CLUSTER_ID_HERE
    platforms:
      openshift:
        enabled: true
        route:
          annotations: {}
          enabled: false
        scc:
          clusterController: true
          networkCosts: true
      cicd:
        enabled: false  # Set to true when using affected CI/CD tools for access to the below configuration options.
        skipSanityChecks: false  # If true, skip all sanity/existence checks for resources like Secrets.
        securityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault