kubecostProductConfigs:
  # clustername should be unique for all clusters, must set this line and cluster_id below
  clusterName: kubecostProductConfigs_clusterName
  # productKey:
  #   key: YOUR_KEY
  #   enabled: true # product key is not needed for eval

federatedETL:
  federatedCluster: true
  agentOnly: true

kubecostModel:
  federatedStorageConfigSecret: kubecost-federated-store
  
global:
  grafana:
    enabled: false
    proxy: false
    
prometheus:
  server:
    global:
      external_labels:
        # cluster_id should be unique for all clusters and the same value as .kubecostProductConfigs.clusterName
        cluster_id: kubecostProductConfigs_clusterName
    retention: 2d