global:
  clusterId: CLUSTER_NAME
  federatedStorage:
    existingSecret: "kubecost-federated-store"
  acknowledged: true

finops-agent:
  enabled: true
aggregator:
  enabled: false
frontend:
  enabled: false
clusterController:
  enabled: false
cloudCost:
  enabled: false
forecasting:
  enabled: false
localStore:
  enabled: false
networkCosts:
  enabled: false