global:
  clusterId: CLUSTER_NAME
  federatedStorage:
    existingSecret: "kubecost-federated-store"
  acknowledged: true

finops-agent:
  enabled: true
  agent:
    collectorDataSource:
      retention1d: 1
    exportIntervals:
      allocation: 14d
      asset: 14d
      networkInsight: 14d
aggregator:
  enabled: false
frontend:
  enabled: false
clusterController:
  enabled: false
cloudCost:
  enabled: false
forecasting:
  enabled: false
localStore:
  enabled: false
networkCosts:
  enabled: false