## Kubecost configuration
global:
  ## @param clusterId The id of the cluster REQUIRED
  ##
  clusterId: cluster-one
  ## @param global.federatedStorage.config The config for the federated storage
  ## @param global.federatedStorage.existingSecret The name of an existing secret to use for the federated storage config. Note, you cannot set both `config` and `existingSecret`.
  ## The name of the Secret containing a bucket config for federated storage.
  ## The contents should be stored under a key named storage-config.yaml by default.
  ## Ref: https://www.ibm.com/docs/en/kubecost/self-hosted/2.x?topic=cluster-long-term-federated-storage-configuration
  federatedStorage:
    config: ""
    # A federated storage config can be provided via an existingSecret or via a string in helm values.
    # If both are provided, the string in helm values take precedence.
    existingSecret: ""
  # fileName: federated-store.yaml  # set this value to change what the file name for the yaml config is
  #cloudIntegrationSecret: cloud-integration # only runs on primary cluster
  platform:
    cicd:
      enabled: true  # Set to true when using affected CI/CD tools for access to the below configuration options.
      skipSanityChecks: true  # If true, skip all sanity/existence checks for resources like Secrets.
## Values for the finops-agent sub-chart
## Ref: https://github.com/kubecost/finops-agent-chart/
##
finopsagent:
  enabled: true
  # serviceAccount:
  #   create: true
  #   name: finops-agent
  agent:
    collectorDataSource:
      enabled: true
      scrapeInterval: 30s
      ## Retention values are for the agent's local store only and do not affect Kubecost history.
      ## These can be increased, but will require more memory.
      retention10m: 6
      retention1h: 3
      retention1d: 2
    exporter:
      ## Emission interval is the interval at which the agent will emit metrics to the object storage.
      ## This can be increased to reduce the number of object (versions) written to the object storage when versioning is enabled.
      emissionInterval: 1m
networkCosts:
  enabled: false
forecasting:
  enabled: false
kubecostProductConfigs:
  productKey:
    enabled: false
    key: ""
    secretname: ""  # Reference an existing k8s secret created from a file named productkey.json of format { "key": "enterprise-key-here" }. If the secretname is specified, a configmap with the key will not be created.
    mountPath: ""  # (use instead of secretname) Declare the path at which the product key file is mounted (eg. "/some/custom/path/productkey.json" by a secrets provisioner). The file must be of format { "key": "enterprise-key-here" }.
## Kubecost Local Store
## When no federated storage bucket is configured, localStore provides local storage via a
## container, PVC, and service for agent and aggregator communication.
##
localStore:
  enabled: true
  

