kubecostProductConfigs:
  # clustername should be unique for all clusters
  clusterName: kubecostProductConfigs_clusterName
  # productKey:
  #   secretname: productkey
  #   enabled: false #not needed for eval
  cloudIntegrationSecret: cloud-integration # only runs on primary cluster

kubecostModel:
  federatedStorageConfigSecret: kubecost-federated-store
  
federatedETL:
  federatedCluster: true
  
prometheus:
  server:
    global:
      external_labels:
        # cluster_id should be unique for all clusters and the same value as .kubecostProductConfigs.clusterName
        cluster_id: kubecostProductConfigs_clusterName
